x-defaults: &defaults
  restart: unless-stopped
  networks:
    - projeto-korp

services:
  http-server-projeto-korp:
    <<: *defaults
    image: http-server-projeto-korp
    container_name: http-server-projeto-korp
    build: ./http-server

  nginx:
    <<: *defaults
    image: nginx:1.30-alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - "./nginx/conf.d:/etc/nginx/conf.d:ro"
    depends_on:
      - http-server-projeto-korp

  prometheus:
    <<: *defaults
    image: prom/prometheus:v3.15.0
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - "./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro"

  grafana:
    <<: *defaults
    build: ./grafana
    container_name: grafana
    ports:
      - 3000:3000
    volumes:
      - "grafana-data:/var/lib/grafana"
      - "./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources:ro"
      - "./grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards:ro"
    depends_on:
      - prometheus
    environment:
      GF_AUTH_ANONYMOUS_ENABLED: "true"
      GF_AUTH_ANONYMOUS_ORG_ROLE: "Viewer"
      GF_DASHBOARDS_DEFAULT_HOME_DASHBOARD_PATH: "/etc/grafana/provisioning/dashboards/http-server-projeto-korp-dashboard.json"

networks:
  projeto-korp:
    name: projeto-korp
    external: true

volumes:
  grafana-data:
