{
 "title": "http-server-projeto-korp",
 "description": "Metricas do serviço http-server do projeto korp",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  { "title": "Disponibilidade", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Disponibilidade",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"http-server-projeto-korp\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disponibilidade no período",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time(up{job=\"http-server-projeto-korp\"}[$__range])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disponibilidade no tempo",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 16, "x": 8, "y": 1 },
   "targets": [
    {
     "expr": "up{job=\"http-server-projeto-korp\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  { "title": "Requisições", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Taxa de erros",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(sum(rate(http_requests_total{job=\"http-server-projeto-korp\", code=~\"4..\"}[$__rate_interval])) or vector(0)) / sum(rate(http_requests_total{job=\"http-server-projeto-korp\"}[$__rate_interval]))",
     "legendFormat": "4xx (cliente)"
    },
    {
     "expr": "(sum(rate(http_requests_total{job=\"http-server-projeto-korp\", code=~\"5..\"}[$__rate_interval])) or vector(0)) / sum(rate(http_requests_total{job=\"http-server-projeto-korp\"}[$__rate_interval]))",
     "legendFormat": "5xx (Servidor)"
    }
   ]
  },
  {
   "title": "Requisições por segundo",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (code) (rate(http_requests_total{job=\"http-server-projeto-korp\"}[$__rate_interval]))",
     "legendFormat": "{{code}}"
    }
   ]
  }
 ]
}